### ISSUE TITLE
it doesn't work

### ISSUE THREAD

**Issue by Joannasims4** [seathasky/gshade_cx_mac#1]
for MacBook users it doesn't work because we have an app called textedit and u can't delete it or anything so that means that on documents like those it changes to texts not installers, please try and actually test this because me and my friend were so. happy until we found out it doesn't work. thanks

**Comment by seathasky** [comment]
Drag the script into terminal, type "sh" space and drag script after.
![script](https://user-images.githubusercontent.com/17598024/171880978-6a28d969-b47f-49c4-8d8a-90e5eda3e839.gif)

**Comment by seathasky** [comment]
Drag the script into terminal, type "sh" space and drag script after.
![kik](https://user-images.githubusercontent.com/17598024/171900314-e526ecec-56a3-4277-a139-9a3eda581012.gif)
