### ISSUE TITLE
Recently , gshade has the lastest version v3.5.1, and I cannot update it in the game...

### ISSUE THREAD

**Issue by Jessie1026** [seathasky/gshade_cx_mac#3]
Hi, I have a problem, recently gshade has the lastest version v3.5.1, and I cannot update it in the game...
and If I dont update to newest version canot use the effects in game... pls help me 😭

**Comment by seathasky** [comment]
Can you try this:
1) Navigate to ~/.local/share/GShade in Finder
2) Delete GShade32.dll and GShade64.dll
3) Replace with these copies attached

https://softwareupdate.xivmac.com/sites/default/files/update_data/gshade_data/GShade32.dll

https://softwareupdate.xivmac.com/sites/default/files/update_data/gshade_data/GShade64.dll
